# Generated by Django 4.1.3 on 2022-11-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('isla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ini', models.IntegerField()),
                ('ent', models.IntegerField()),
                ('sal', models.IntegerField()),
                ('fin', models.IntegerField()),
                ('fecha', models.DateField()),
                ('isla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isla.isla')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
