# Generated by Django 3.2.6 on 2022-11-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
        migrations.AddField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
