# Generated by Django 3.2.6 on 2022-11-30 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20221128_1638'),
        ('inventario', '0005_auto_20221129_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='producto.producto', unique=True),
            preserve_default=False,
        ),
    ]
