# Generated by Django 3.2.6 on 2022-11-30 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20221129_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariomovimientos',
            name='inventario',
        ),
    ]
