# Generated by Django 3.2.6 on 2022-11-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_remove_inventariomovimientos_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariomovimientos',
            name='inventario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario'),
            preserve_default=False,
        ),
    ]
