# Generated by Django 4.1.3 on 2022-11-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('Passport', 'Passport')], max_length=8)),
                ('isla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isla.isla')),
            ],
        ),
    ]
