# Generated by Django 3.2.6 on 2022-11-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='T0000', max_length=100, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
