# Generated by Django 4.1.3 on 2022-11-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(choices=[('CC', 'CC'), ('TI', 'TI'), ('CE', 'CE'), ('Passport', 'Passport')], max_length=8)),
            ],
        ),
    ]
