# Generated by Django 3.2.6 on 2022-11-28 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturadetalle',
            name='producto',
        ),
    ]
