# Generated by Django 4.1.3 on 2022-11-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha',
            field=models.DateField(default='2002-11-09'),
            preserve_default=False,
        ),
    ]
