# Generated by Django 3.2.6 on 2022-11-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20221128_1638'),
        ('factura', '0002_remove_facturadetalle_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturadetalle',
            name='producto',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='producto.producto'),
            preserve_default=False,
        ),
    ]
