# Generated by Django 3.2.6 on 2022-11-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_facturadetalle_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.CharField(max_length=10),
        ),
    ]
